### ISSUE TITLE
New cyrrilic font sucks...

### ISSUE THREAD

**Issue by dadyarri** [ksylor/ohshitgit#23]
IMHO, new font rendering too bad on russian language in italic and mono versions.
My opinion about font pairings:
- Montserrat (titles)
- Roboto (main)
- Jetbrains Mono (code)

![Screenshot_20200420_202222](https://user-images.githubusercontent.com/51821039/79780703-f767a100-8344-11ea-96c8-95a97a76c18d.png)

**Comment by ksylor** [comment]
Okay so, I did some investigation and the Source Sans Pro font doesn't have any italic glyphs in Cyrillic, so the browser is falling back to the system font for italics.

![image](https://user-images.githubusercontent.com/1698740/86540869-1ef6f000-bed6-11ea-8001-849c647c8009.png)

I played around with a few options and I'm going to go with Open Sans - It feels really good to me! 

Updated in https://github.com/ksylor/ohshitgit/commit/b39ee0275e3b3898782484ebaed7f0424a5b034d
