### ISSUE TITLE
Why must language be so repulsive? It makes your great work bad :-(

### ISSUE THREAD

**Issue by schittli** [ksylor/ohshitgit#50]
Hello

It is a real pity and a shame that this great tutorial uses such repulsive terms. 
They're neither cool nor useful - but they're messing up the great work.

Your work would have been worth far more than 6 watcher - but maybe it's just for personal use anyway.

Kind regards,
Thomas

**Comment by dadyarri** [comment]
Hello, there is a disclaimer in the end of page:
> ...I've come to these steps through trial and error and lots of swearing and table flipping, and I had this crazy idea to share them with a healthy dose of levity and profanity. Take it or leave it as you will!

If this terms offend or embarrass you, there is a non-swear version: https://dangitgit.com
Sincerely, Daniil
