### ISSUE TITLE
Add verbosity to rm command

### ISSUE THREAD

**Issue by xearonet** [ksylor/ohshitgit#57]
regarding this https://ohshitgit.com/#fuck-this-noise

you can add `-v` to command because when you realize you fucked up, you at least know what you deleted
```
sudo rm -v -r fucking-git-repo-dir
```

**Comment by clementFoyer** [comment]
Why is the `sudo` required for this command? If it is to silence the warning when trying to delete protected objects, `rm -rf fucking-git-repo-dir` is usually sufficient.

**Comment by xearonet** [comment]
Good point @clementFoyer 👍 
I don't know. I took original command and add verbosity. Now when you pointed that, really idk for what this `sudo` could be necessary in this particular command.
Maybe author stores repos in `/codeMF` 😂
Stay safe ✋
